export const ADD_PURCHASE = 'ADD_PURCHASE';
export const EDIT_PURCHASE = 'EDIT_PURCHASE';
export const DELETE_PURCHASE = 'DELETE_PURCHASE';

export const CHANGE_MODAL_STATE = 'CHANGE_MODAL_STATE';

export const UPDATE_IDS_IN_TABLE_STATE = 'UPDATE_ID_IN_TABLE_STATE';

export const CHANGE_PURCHASED = 'CHANGE_PURCHASED';
